[colors.bright]
black = "0x3c3836"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[colors.normal]
black = "0x3c3836"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[colors.primary]
background = "0x1d2021"
foreground = "0xd4be98"

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.bold]
family = "BerkeleyMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Berkeley Mono"
style = "Bold Italic"

[font.italic]
family = "BerkeleyMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "BerkeleyMono Nerd Font Mono"
style = "Regular"

[terminal.shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/usr/local/bin/fish"

[window]
dynamic_padding = false
opacity = 1
startup_mode = "Windowed"

[window.dimensions]
columns = 133
lines = 40

[window.padding]
x = 1
y = 1
