theme = "gruvbox"

[editor]
mouse = true
bufferline = "always"
cursorline = true
line-number = "relative"
completion-trigger-len = 2
color-modes	= true
rulers = [120]
auto-save = true
auto-pairs = true
scrolloff = 10

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false
git-ignore = true	

[editor.lsp]
display-messages = true
display-signature-help-docs	= false
auto-signature-help	= true

[editor.statusline]
left = ["mode", "version-control", "file-name", "spinner"]
right = ["workspace-diagnostics", "file-type"]

[keys.normal]
esc = ["keep_primary_selection", "collapse_selection"]
C-q = [":buffer-close"]
"space" = {e = ":fmt"}
H = ["goto_first_nonwhitespace"]
L = ["goto_line_end"]
";" = ["trim_selections"]
C-v = ["copy_selection_on_next_line"]
D = ["ensure_selections_forward", "kill_to_line_end"]
C = ["ensure_selections_forward", "kill_to_line_end", "insert_mode"]
C-r = ["redo"]
"'" = ["repeat_last_motion"]
G = ["goto_last_line"]
m = {w = ["move_next_word_start", "move_prev_word_start"]} # match word

[keys.select]
H = ["goto_first_nonwhitespace"]
L = ["goto_line_end"]
C-v = ["copy_selection_on_next_line"]
";" = ["trim_selections"]
"'" = ["repeat_last_motion"]
G = ["goto_last_line"]
m = {w = ["move_next_word_start", "move_prev_word_start"]} # match word

[editor.indent-guides]
render = true

[keys.insert]
C-u = "kill_to_line_start"
C-l = "delete_char_forward"
