theme = "gruvbox"

[editor]
true-color = true
completion-replace = false
mouse = true
bufferline = "always"
cursorline = true
line-number = "absolute"
completion-trigger-len = 2
color-modes	= true
# rulers = [150]
auto-save = true
auto-pairs = true
scrolloff = 10

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false
git-ignore = true	

[editor.lsp]
display-messages = true
display-signature-help-docs	= false
auto-signature-help	= true
display-diagnostic-message = true

[editor.lsp.inline-diagnostics]
cursor-line = "warning"
# other-lines = "error"

[editor.statusline]
left = ["mode", "version-control", "file-name", "read-only-indicator", "file-modification-indicator", "spinner"]
right = ["workspace-diagnostics", "file-type", "total-line-numbers", "position"]

[keys.normal]
esc = ["keep_primary_selection", "collapse_selection"]
C-q = [":buffer-close"]
"space" = {e = ":fmt", l = ":reload-all", "space" = ":w"}
H = ["goto_first_nonwhitespace"]
L = ["goto_line_end"]
";" = ["trim_selections"]
V = ["copy_selection_on_next_line"]
D = ["collapse_selection", "kill_to_line_end"]
C = ["collapse_selection", "kill_to_line_end", "insert_mode"]
C-r = ["redo"]
"'" = ["repeat_last_motion"]
G = ["goto_last_line"]
m = {w = ["move_next_word_start", "move_prev_word_start"]} # match word

[keys.select]
H = ["goto_first_nonwhitespace"]
L = ["goto_line_end"]
C-v = ["copy_selection_on_next_line"]
";" = ["trim_selections"]
"'" = ["repeat_last_motion"]
G = ["goto_last_line"]
m = {w = ["move_next_word_start", "move_prev_word_start"]} # match word

[editor.indent-guides]
render = true

[keys.insert]
C-u = "kill_to_line_start"
C-l = "delete_char_forward"

[keys.normal.g]
B = ":pipe-to tmux popup -d '#{pane_current_path}' -h 90% -w 90% -E ~/.tmux-git-blame.sh"
