[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
max_completion_items = 10     # set max completion results len for each group: words, snippets, unicode-input
snippets_first = false         # completions will return before snippets by default
feature_words = true          # enable completion by word
feature_snippets = false       # enable snippets
feature_unicode_input = false  # enable "unicode input" (experimental feature)

[language-server.gopls]
command = "gopls"

[language-server.gopls.config]
goimports = true

[language-server.gopls.config.hints]
assignVariableTypes = true
compositeLiteralFields = true
constantValues = true
functionTypeParameters = true
parameterNames = true
rangeVariableTypes = true

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
cargo.allFeatures = true
chekOnSave.command = "clippy"
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false

[language-server.pyright.config]
python.analysis.typeCheckingMode = "off"

[[language]]
name = "python"
language-servers = ["pyright", "scls"]

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "scls"]

[[language]]
name = "go"
language-servers = ["gopls", "scls"]

[[language]]
name = "scala"
language-servers = ["metals", "scls"]

[[language]]
name = "yaml"
scope = "source.yaml"
file-types = ["yml", "yaml"]
indent = { tab-width = 2, unit = "  " }
language-servers = ["yaml-language-server", "scls"]
injection-regex = "yml|yaml"
