# [[language]]
# name = "scala"
# scope = "source.scala"
# roots = ["build.sbt", "build.sc", "build.gradle", "pom.xml", ".scala-build"]
# file-types = ["scala", "sbt", "sc"]
# comment-token = "//"
# indent = { tab-width = 2, unit = "  " }
# language-server = { command = "metals" }
# config = { "isHttpEnabled" = true, "metals.ammoniteJvmProperties" = ["-Xmx1G"]}
# config = {metals = {showImplicitArguments = false, showInferredType = false, showImplicitConversionsAndClasses = false,superMethodLensesEnabled = false, ammoniteJvmProperties = ["-Xmx2G"]}}

[[language]]
name = "python"
roots = ["pyproject.toml"]
language-server = { command = "pyright-langserver", args = ["--stdio"] }
config = {} # <- this is the important line
