os:
    edit: tmux send-keys -t "top-left" ":o {{filename}}" Enter
    editAtLine: tmux send-keys -t "top-left" ":o {{filename}}:{{line}}" Enter
    open: tmux send-keys -t "top-left" ":o {{filename}}" Enter
    openLink: open {{link}}
    editInTerminal: false
