local palette = require("colors.palette")

return {
    NvimTreeSymlink=palette.Fg,
    NvimTreeFolderName=palette.Green,
    NvimTreeRootFolder=palette.Grey,
    NvimTreeFolderIcon=palette.Orange,
    NvimTreeEmptyFolderName=palette.Green,
    NvimTreeOpenedFolderName=palette.Green,
    NvimTreeExecFile=palette.Fg,
    NvimTreeOpenedFile=palette.Fg,
    NvimTreeSpecialFile=palette.Fg,
    NvimTreeImageFile=palette.Fg,
    NvimTreeMarkdownFile=palette.Fg,
    NvimTreeIndentMarker=palette.Grey,
    NvimTreeGitDirty=palette.Yellow,
    NvimTreeGitStaged=palette.Blue,
    NvimTreeGitMerge=palette.Orange,
    NvimTreeGitRenamed=palette.Purple,
    NvimTreeGitNew=palette.Aqua,
    NvimTreeGitDeleted=palette.Red,
    NvimTreeLspDiagnosticsError=palette.RedSign,
    NvimTreeLspDiagnosticsWarning=palette.YellowSign,
    NvimTreeLspDiagnosticsInformation=palette.BlueSign,
    NvimTreeLspDiagnosticsHint=palette.GreenSign,
}
