local palette = require("colors.palette")
local utils = require("colors.utils")
local prop = utils.prop

return {
    CmpItemAbbrMatch=prop(palette.green,palette.none, 'bold'),
    CmpItemAbbrMatchFuzzy=prop(palette.green,palette.none, 'bold'),
    CmpItemAbbr=palette.Fg,
    CmpItemAbbrDeprecated=palette.Fg,
    CmpItemMenu=palette.Fg,
    CmpItemKind=palette.Yellow,
    CmpItemKindText=palette.Fg,
    CmpItemKindMethod=palette.Green,
    CmpItemKindFunction=palette.Green,
    CmpItemKindConstructor=palette.Green,
    CmpItemKindField=palette.Green,
    CmpItemKindVariable=palette.Blue,
    CmpItemKindClass=palette.Yellow,
    CmpItemKindInterface=palette.Yellow,
    CmpItemKindModule=palette.Yellow,
    CmpItemKindProperty=palette.Blue,
    CmpItemKindUnit=palette.Purple,
    CmpItemKindValue=palette.Purple,
    CmpItemKindEnum=palette.Yellow,
    CmpItemKindKeyword=palette.Red,
    CmpItemKindSnippet=palette.Aqua,
    CmpItemKindColor=palette.Aqua,
    CmpItemKindFile=palette.Aqua,
    CmpItemKindReference=palette.Aqua,
    CmpItemKindFolder=palette.Aqua,
    CmpItemKindEnumMember=palette.Purple,
    CmpItemKindConstant=palette.Blue,
    CmpItemKindStruct=palette.Yellow,
    CmpItemKindEvent=palette.Orange,
    CmpItemKindOperator=palette.Orange,
    CmpItemKindTypeParameter=palette.Yellow,
}
